site_name: Project Vera
repo_url: https://github.com/project-vera/vera
repo_name: vera
nav:
  - Mission: index.md
  - Publications: pubs/pubs.md
  - Emulators:
    - Amazon EC2 Emulator: vera-aws.md
    - Google Compute Engine: vera-gcp.md
  - Blogs:
    - "[02-06-2026] No More Manual Mocks.": blogs/cloudemu/cloudemu.md
    - "[02-06-2026] The quest for AI Agents as DevOps.": blogs/cloudagent/cloudagent.md

theme:
  name: material
  logo: assets/images/icon3-3.svg
  favicon: assets/images/icon3-3.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: white
      accent: black
      font:
        text: Roboto
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: white
      font:
        text: Roboto
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - include-markdown
  